### ISSUE TITLE
Week 07 Day 2  - Let's go to the Vue-vies - 

### ISSUE THREAD

**Issue by mdewey** [rochaproforma/assignments#26]
Using a the movie APIs, you will be creating a sample project to continue working with Vue.js

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Use this API [https://developers.themoviedb.org/3/getting-started/introduction](https://developers.themoviedb.org/3/getting-started/introduction)
    - You will have to create an account to get a key, Feel free to use the address and phone number of campus to sign up with
- Create a simple UI that allows for Users to search for a movie
- You will be using this endpoint = [https://developers.themoviedb.org/3/search/search-movies](https://developers.themoviedb.org/3/search/search-movies)

### Explorer Mode

- [x] Create a page that has a textbox that allows the user to type in a search term.
- [ ] Using the endpoint above, pass the endpoint what the user typed in and display the results,
- [x] Style your page to make your website look like a modern site.
- [x] Add a Section to your page that shows the user the trending movies. Use this endpoint: [https://developers.themoviedb.org/3/trending/get-trending](https://developers.themoviedb.org/3/trending/get-trending)

### Adventure Mode

- [ ] Allow the user to save movies to local storage to look at later
- [ ] Allow the user to search both TV shows and Movies
- [ ] Using Vue-Router, set up the site to handle so a use can see more data about a movie or tv show
- [ ] Explore the API and use any endpoints you find interesting

**Comment by jsonrocha** [comment]
https://github.com/rochaproforma/vue_api

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/fndxOK4hOSi5rWgBiP/200w_d.gif)
