### ISSUE TITLE
Final Project 1 - It starts with a plan. - 

### ISSUE THREAD

**Issue by mdewey** [rochaproforma/assignments#27]
We are starting the final stretch of the cohort. This means we are starting to focus on our final projects. 

When we go to start a new project. The first step is create an elevator pitch. This is a short description that describes what your final project is doing. This should be simliar to what you said last week for lab.

The second step is to always plan out what we are doing. These early plans often take the shape of wire frames. This means that our first task for the capstone projects is create our wire frames.

The elevator pitch wire frames should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed, but must be changed with purpose.

## Objectives

* Finalize the idea for your capstone
* Create wire frames for your capstone project

## Requirements

* Using your favorite way to create wire frames (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are. 
* Create a new repository for your capstone project

### Explorer Mode, Due Friday 9/7

* [x] Create the elevator pitch for your final projects. 
* [x] Place this in the `README.md` of your capstone project repository 

### Explorer Mode, Due Monday 9/10
* [x] Create a wire frame for each page in your page you capstone. 
* [x] Place these wire frames in an `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.

**Comment by jsonrocha** [comment]
[Tide-Tracker-API.pdf](https://github.com/rochaproforma/assignments/files/2358793/Tide-Tracker-API.pdf)

**Comment by jsonrocha** [comment]
Rough first draft

**Comment by mdewey** [comment]
I like the UI. Can you also post the API/website you plan on getting the data from?

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/rafLFavz9V6YU/200w_d.gif)

**Comment by jsonrocha** [comment]
@mdewey 
I added the README.md elevator pitch.

Here is the map that I am going to try and mimic with google maps and markers for the weather stations: https://tidesandcurrents.noaa.gov/map/

And then I would link to that city's weather station and the data will come from here and look like this: 
https://tidesandcurrents.noaa.gov/stationhome.html?id=8726384
