### ISSUE TITLE
Week 08 Day 3 - INSERT INTO Student (knowledge) VALUES ('SQL') - 

### ISSUE THREAD

**Issue by mdewey** [rochaproforma/assignments#31]
Every application uses data in some way. This will help you set up your development environment as well as get used to querying databases. 

## Objectives

* Install Postgres
* Create a database for Employees
* Write some queries to use the database

### For Mac: 

Use homebrew to install Postgres 

``` 
brew install postgres
```

### Windows: 

- head here and download the install https://www.enterprisedb.com/downloads/postgres-postgresql-downloads and follow the prompts

### Explorer Mode

* [x] Install Postgres
* [x] Create a database called `CompanyDatabase`
* [x] Create a table Called `Employees`
* [x] Add the following columns to the table, Use your best judgement for data types
    - Id (Primary Key)
    - FullName
    - Salary
    - Position
    - PhoneExtension
    - IsPartTime

* [x] Create queries that can do the following:
    - [x] Select all columns for all employees
    - [x] Select only the FullName and Phone Extension for Only Full Time employees
    - [x] Insert a new Part time employee, as a software developer, part time, with a salary of 450
    - [x] Update all Employees that are the Cooks to have a salary of 500
    - [x] Delete all Employees that have the full name of "Lazy Lynn"
    - [x] Update all Employees to be full time
    - [x] Add a column to the table called `ParkingSpotNumber` as a string that up to 10 characters long

* [x] Turn in the above queries as a gist 
 

### Adventure Mode

* [x] Work on the C# Koans
* [x] Work on your final project

### Epic Mode

* [ ] Investigate working with C# and Postgres

## Additional Resources

* [https://www.postgresql.org/docs/10/static/index.html](https://www.postgresql.org/docs/10/static/index.html
)
## Recommended Practice:

* For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by jsonrocha** [comment]
https://gist.github.com/rochaproforma/632b4f2408b02afd660b8dc3d39c7f00

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/xWYQ6Szb7ziwmJEvzl/200w_d.gif)
