### ISSUE TITLE
Week 01 Weekend - Portfolio - 

### ISSUE THREAD

**Issue by mdewey** [rochaproforma/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career. 

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your own personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.

### Adventure Mode

- [x] Take the time to personalize the site.
- [x] Keep it professional, but make it your own.

**Comment by jsonrocha** [comment]
https://github.com/rochaproforma/weekend1

**Comment by mdewey** [comment]
be sure to keep your HTML properly indented.

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/l3q2DbzOZjFYNflII/200w_d.gif)

**Comment by jsonrocha** [comment]
https://github.com/rochaproforma/weekend1
