### ISSUE TITLE
Final Project 4 - #Ship it - 

### ISSUE THREAD

**Issue by mdewey** [rochaproforma/assignments#43]
With all the work you have been putting into the last 12 weeks, it has all come down to this. Complete your capstone and show it to the world

## Explorer Mode

- [x] Submit your repository for the capstone project
- [ ] Submit your Url(s) for your capstone project.

**Comment by jsonrocha** [comment]
https://github.com/rochaproforma/tidetracker

**Comment by jsonrocha** [comment]
tidetracker.live

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/3o7aCQNE8LAwzhucRW/200w_d.gif)
